# Generated by Django 5.1.4 on 2025-05-22 17:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_cache', models.JSONField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TblClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='TblCoiffeuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Coiffeuse',
                'verbose_name_plural': 'Coiffeuses',
            },
        ),
        migrations.CreateModel(
            name='TblEmailStatus',
            fields=[
                ('idTblEmailStatus', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TblEmailType',
            fields=[
                ('idTblEmailType', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TblLocalite',
            fields=[
                ('idTblLocalite', models.AutoField(primary_key=True, serialize=False)),
                ('commune', models.CharField(max_length=40)),
                ('code_postal', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TblMethodePaiement',
            fields=[
                ('idTblMethodePaiement', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TblNumeroTVA',
            fields=[
                ('idTblNumeroTVA', models.AutoField(primary_key=True, serialize=False)),
                ('numero_tva', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblPaiementStatut',
            fields=[
                ('idTblPaiementStatut', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TblPrix',
            fields=[
                ('idTblPrix', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
        migrations.CreateModel(
            name='TblRole',
            fields=[
                ('idTblRole', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblService',
            fields=[
                ('idTblService', models.AutoField(primary_key=True, serialize=False)),
                ('intitule_service', models.CharField(max_length=100)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(600)])),
            ],
        ),
        migrations.CreateModel(
            name='TblSexe',
            fields=[
                ('idTblSexe', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblTemps',
            fields=[
                ('idTblTemps', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('minutes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TblType',
            fields=[
                ('idTblType', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_user', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hairbnb.aiconversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TblCoiffeuseSalon',
            fields=[
                ('idCoiffeuseSalon', models.AutoField(primary_key=True, serialize=False)),
                ('est_proprietaire', models.BooleanField(default=False)),
                ('coiffeuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois', to='hairbnb.tblcoiffeuse')),
            ],
        ),
        migrations.CreateModel(
            name='TblIndisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('coiffeuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='hairbnb.tblcoiffeuse')),
            ],
        ),
        migrations.AddField(
            model_name='tblcoiffeuse',
            name='numero_tva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coiffeuses', to='hairbnb.tblnumerotva'),
        ),
        migrations.CreateModel(
            name='TblRendezVous',
            fields=[
                ('idRendezVous', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('confirmé', 'Confirmé'), ('annulé', 'Annulé'), ('terminé', 'Terminé')], default='en attente', max_length=20)),
                ('total_prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duree_totale', models.PositiveIntegerField(blank=True, null=True)),
                ('est_archive', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='hairbnb.tblclient')),
                ('coiffeuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='hairbnb.tblcoiffeuse')),
            ],
        ),
        migrations.CreateModel(
            name='TblPaiement',
            fields=[
                ('idTblPaiement', models.AutoField(primary_key=True, serialize=False)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email_client', models.EmailField(blank=True, max_length=30, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=255, null=True)),
                ('methode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hairbnb.tblmethodepaiement')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hairbnb.tblpaiementstatut')),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairbnb.tblrendezvous')),
            ],
        ),
        migrations.CreateModel(
            name='TblRue',
            fields=[
                ('idTblRue', models.AutoField(primary_key=True, serialize=False)),
                ('nom_rue', models.CharField(max_length=100)),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rues', to='hairbnb.tbllocalite')),
            ],
            options={
                'unique_together': {('nom_rue', 'localite')},
            },
        ),
        migrations.CreateModel(
            name='TblAdresse',
            fields=[
                ('idTblAdresse', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=5)),
                ('rue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adresses', to='hairbnb.tblrue')),
            ],
        ),
        migrations.CreateModel(
            name='TblSalon',
            fields=[
                ('idTblSalon', models.AutoField(primary_key=True, serialize=False)),
                ('nom_salon', models.CharField(max_length=30)),
                ('slogan', models.CharField(blank=True, max_length=40, null=True)),
                ('a_propos', models.TextField(blank=True, max_length=700, null=True)),
                ('logo_salon', models.ImageField(blank=True, default='photos/defaults/logo_default.png', null=True, upload_to='photos/logos/')),
                ('position', models.CharField(default='0,0', help_text="Format: 'latitude,longitude'", max_length=50)),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to='hairbnb.tbladresse')),
                ('coiffeuses', models.ManyToManyField(related_name='salons', through='hairbnb.TblCoiffeuseSalon', to='hairbnb.tblcoiffeuse')),
                ('numero_tva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to='hairbnb.tblnumerotva')),
            ],
        ),
        migrations.AddField(
            model_name='tblrendezvous',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='hairbnb.tblsalon'),
        ),
        migrations.AddField(
            model_name='tblcoiffeusesalon',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='hairbnb.tblsalon'),
        ),
        migrations.CreateModel(
            name='TblAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')])),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hairbnb.tblclient')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='hairbnb.tblsalon')),
            ],
        ),
        migrations.CreateModel(
            name='TblSalonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/salon/')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hairbnb.tblsalon')),
            ],
        ),
        migrations.CreateModel(
            name='TblSalonService',
            fields=[
                ('idSalonService', models.AutoField(primary_key=True, serialize=False)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_service', to='hairbnb.tblsalon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_service', to='hairbnb.tblservice')),
            ],
            options={
                'unique_together': {('salon', 'service')},
            },
        ),
        migrations.AddField(
            model_name='tblsalon',
            name='services',
            field=models.ManyToManyField(related_name='salons', through='hairbnb.TblSalonService', to='hairbnb.tblservice'),
        ),
        migrations.CreateModel(
            name='TblPromotion',
            fields=[
                ('idPromotion', models.AutoField(primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='hairbnb.tblservice')),
            ],
        ),
        migrations.CreateModel(
            name='TblTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('paiement', 'Paiement'), ('remboursement', 'Remboursement')], max_length=13)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('effectué', 'Effectué'), ('en attente', 'En attente')], max_length=20)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='hairbnb.tblpaiement')),
            ],
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('idTblUser', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('photo_profil', models.ImageField(blank=True, default='photos/defaults/avatar.png', null=True, upload_to='photos/profils/')),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='utilisateurs', to='hairbnb.tbladresse')),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='utilisateurs', to='hairbnb.tblrole')),
                ('sexe_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='hairbnb.tblsexe')),
                ('type_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='hairbnb.tbltype')),
            ],
        ),
        migrations.AddField(
            model_name='tblpaiement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hairbnb.tbluser'),
        ),
        migrations.CreateModel(
            name='TblEmailNotification',
            fields=[
                ('idTblEmailNotification', models.AutoField(primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='hairbnb.tblemailstatus')),
                ('type_email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='hairbnb.tblemailtype')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_notification', to='hairbnb.tblrendezvous')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_envoyes', to='hairbnb.tblsalon')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_recus', to='hairbnb.tbluser')),
            ],
            options={
                'verbose_name': 'Notification par email',
                'verbose_name_plural': 'Notifications par email',
                'db_table': 'TblEmailNotification',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='tblcoiffeuse',
            name='idTblUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coiffeuse', to='hairbnb.tbluser'),
        ),
        migrations.AddField(
            model_name='tblclient',
            name='idTblUser',
            field=models.ForeignKey(db_column='idTblUser', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='hairbnb.tbluser'),
        ),
        migrations.CreateModel(
            name='TblCart',
            fields=[
                ('idTblCart', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='hairbnb.tbluser')),
            ],
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='hairbnb.tbluser'),
        ),
        migrations.CreateModel(
            name='TblHoraireCoiffeuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('coiffeuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='hairbnb.tblcoiffeuse')),
            ],
            options={
                'unique_together': {('coiffeuse', 'jour')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='tblcoiffeusesalon',
            unique_together={('coiffeuse', 'salon')},
        ),
        migrations.CreateModel(
            name='TblRendezVousService',
            fields=[
                ('idRendezVousService', models.AutoField(primary_key=True, serialize=False)),
                ('prix_applique', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duree_estimee', models.PositiveIntegerField(blank=True, null=True)),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_services', to='hairbnb.tblrendezvous')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_services', to='hairbnb.tblservice')),
            ],
            options={
                'unique_together': {('rendez_vous', 'service')},
            },
        ),
        migrations.CreateModel(
            name='TblCartItem',
            fields=[
                ('idTblCartItem', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hairbnb.tblcart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='hairbnb.tblservice')),
            ],
            options={
                'unique_together': {('cart', 'service')},
            },
        ),
        migrations.CreateModel(
            name='TblServicePrix',
            fields=[
                ('idServicePrix', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_services', to='hairbnb.tblprix')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prix', to='hairbnb.tblservice')),
            ],
            options={
                'unique_together': {('service',)},
            },
        ),
        migrations.CreateModel(
            name='TblServiceTemps',
            fields=[
                ('idServiceTemps', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_temps', to='hairbnb.tblservice')),
                ('temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps_services', to='hairbnb.tbltemps')),
            ],
            options={
                'unique_together': {('service', 'temps')},
            },
        ),
        migrations.CreateModel(
            name='TblFavorite',
            fields=[
                ('idTblFavorite', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='hairbnb.tblsalon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='hairbnb.tbluser')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'unique_together': {('user', 'salon')},
            },
        ),
    ]
