# Generated by Django 5.1.4 on 2025-05-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrole',
            name='nom',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
