# Generated by Django 5.1.4 on 2025-05-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0002_alter_tblrole_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcoiffeuse',
            name='numero_tva',
        ),
        migrations.AlterField(
            model_name='tblcoiffeuse',
            name='nom_commercial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblsalon',
            name='numero_tva',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
