# Generated by Django 5.1.4 on 2025-05-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0003_remove_tblcoiffeuse_numero_tva_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblNumeroTVA',
        ),
    ]
