# Generated by Django 5.1.4 on 2025-05-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0004_delete_tblnumerotva'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCategorie',
            fields=[
                ('idTblCategorie', models.AutoField(primary_key=True, serialize=False)),
                ('intitule_categorie', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tblindisponibilite',
            name='motif',
            field=models.CharField(default='Non spécifié', max_length=60),
            preserve_default=False,
        ),
    ]
