# Generated by Django 5.1.4 on 2025-05-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0005_tblcategorie_alter_tblindisponibilite_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblservice',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hairbnb.tblcategorie'),
        ),
    ]
