# Generated by Django 5.1.4 on 2025-05-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0006_tblservice_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrue',
            name='nom_rue',
            field=models.CharField(max_length=50),
        ),
    ]
