# Generated by Django 5.1.4 on 2025-05-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0007_alter_tblrue_nom_rue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='prenom',
            field=models.CharField(max_length=20),
        ),
    ]
