# Generated by Django 5.1.4 on 2025-05-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0008_alter_tbluser_nom_alter_tbluser_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrole',
            name='nom',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
