# Generated by Django 5.1.4 on 2025-06-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0009_alter_tblrole_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='photo_profil',
            field=models.ImageField(default='assets/logo_login/avatar.png', upload_to='photos/profils/'),
        ),
    ]
