# Generated by Django 5.1.4 on 2025-06-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0010_alter_tbluser_photo_profil'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblserviceprix',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tblservicetemps',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tblserviceprix',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prix_services', to='hairbnb.tblsalon'),
        ),
        migrations.AddField(
            model_name='tblservicetemps',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temps_services', to='hairbnb.tblsalon'),
        ),
    ]
