# Generated by Django 5.1.4 on 2025-06-08 01:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0011_alter_tblserviceprix_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblpromotion',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AddField(
            model_name='tblpromotion',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='hairbnb.tblsalon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblpromotion',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='tblpromotion',
            unique_together={('salon', 'service', 'start_date')},
        ),
    ]
