# Generated by Django 5.1.4 on 2025-06-11 18:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0012_alter_tblpromotion_options_tblpromotion_salon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAvisStatut',
            fields=[
                ('idTblAvisStatut', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Statut d'avis",
                'verbose_name_plural': "Statuts d'avis",
                'db_table': 'tbl_avis_statut',
                'ordering': ['libelle'],
            },
        ),
        migrations.AlterModelOptions(
            name='tblavis',
            options={'ordering': ['-date_avis'], 'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
        migrations.AddField(
            model_name='tblavis',
            name='coiffeuse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to='hairbnb.tblcoiffeuse'),
        ),
        migrations.AddField(
            model_name='tblavis',
            name='date_avis',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tblavis',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tblavis',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tblavis',
            name='date_reponse_coiffeuse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblavis',
            name='motif_moderation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblavis',
            name='recommande_coiffeuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblavis',
            name='recommande_salon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblavis',
            name='rendez_vous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='hairbnb.tblrendezvous'),
        ),
        migrations.AddField(
            model_name='tblavis',
            name='reponse_coiffeuse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='tblavis',
            table='TblAvis',
        ),
        migrations.AddField(
            model_name='tblavis',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avis', to='hairbnb.tblavisstatut'),
        ),
        migrations.AddIndex(
            model_name='tblavis',
            index=models.Index(fields=['salon', 'statut'], name='TblAvis_salon_i_d3bcf5_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavis',
            index=models.Index(fields=['coiffeuse', 'statut'], name='TblAvis_coiffeu_573daf_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavis',
            index=models.Index(fields=['client'], name='TblAvis_client__2edf7a_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavis',
            index=models.Index(fields=['date_avis'], name='TblAvis_date_av_6c89f2_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavis',
            index=models.Index(fields=['rendez_vous'], name='TblAvis_rendez__54d5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavis',
            index=models.Index(fields=['statut'], name='TblAvis_statut__79973f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tblavis',
            constraint=models.CheckConstraint(condition=models.Q(('note__gte', 1), ('note__lte', 5)), name='tblavis_note_valide_v2'),
        ),
        migrations.AddConstraint(
            model_name='tblavis',
            constraint=models.UniqueConstraint(condition=models.Q(('rendez_vous__isnull', False)), fields=('rendez_vous',), name='tblavis_un_avis_par_rdv_v2'),
        ),
    ]
