# Generated by Django 5.1.4 on 2025-06-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0013_tblavisstatut_alter_tblavis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblavis',
            name='statut',
        ),
        migrations.AlterModelOptions(
            name='tblavis',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='tblavis',
            name='tblavis_note_valide_v2',
        ),
        migrations.RemoveConstraint(
            model_name='tblavis',
            name='tblavis_un_avis_par_rdv_v2',
        ),
        migrations.RemoveIndex(
            model_name='tblavis',
            name='TblAvis_salon_i_d3bcf5_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblavis',
            name='TblAvis_coiffeu_573daf_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblavis',
            name='TblAvis_client__2edf7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblavis',
            name='TblAvis_date_av_6c89f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblavis',
            name='TblAvis_rendez__54d5b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblavis',
            name='TblAvis_statut__79973f_idx',
        ),
        migrations.RemoveField(
            model_name='tblavis',
            name='coiffeuse',
        ),
        migrations.RemoveField(
            model_name='tblavis',
            name='date_avis',
        ),
        migrations.RemoveField(
            model_name='tblavis',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='tblavis',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='tblavis',
            name='date_reponse_coiffeuse',
        ),
        migrations.RemoveField(
            model_name='tblavis',
            name='motif_moderation',
        ),
        migrations.RemoveField(
            model_name='tblavis',
            name='recommande_coiffeuse',
        ),
        migrations.RemoveField(
            model_name='tblavis',
            name='recommande_salon',
        ),
        migrations.RemoveField(
            model_name='tblavis',
            name='rendez_vous',
        ),
        migrations.RemoveField(
            model_name='tblavis',
            name='reponse_coiffeuse',
        ),
        migrations.AlterModelTable(
            name='tblavis',
            table=None,
        ),
        migrations.DeleteModel(
            name='TblAvisStatut',
        ),
    ]
