# Generated by Django 5.1.4 on 2025-06-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0014_remove_tblavis_statut_alter_tblavis_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAvisStatut',
            fields=[
                ('idTblAvisStatut', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Statut d'avis",
                'verbose_name_plural': "Statuts d'avis",
                'db_table': 'tbl_avis_statut',
                'ordering': ['libelle'],
            },
        ),
        migrations.AlterModelOptions(
            name='tblavis',
            options={'ordering': ['-date'], 'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
        migrations.AddField(
            model_name='tblavis',
            name='rendez_vous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='hairbnb.tblrendezvous', unique=True),
        ),
        migrations.AlterModelTable(
            name='tblavis',
            table='TblAvis',
        ),
        migrations.AddField(
            model_name='tblavis',
            name='statut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='avis', to='hairbnb.tblavisstatut'),
        ),
        migrations.AddIndex(
            model_name='tblavis',
            index=models.Index(fields=['salon', 'statut'], name='TblAvis_salon_i_d3bcf5_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavis',
            index=models.Index(fields=['client'], name='TblAvis_client__2edf7a_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavis',
            index=models.Index(fields=['rendez_vous'], name='TblAvis_rendez__54d5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavis',
            index=models.Index(fields=['statut'], name='TblAvis_statut__79973f_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavis',
            index=models.Index(fields=['date'], name='TblAvis_date_161162_idx'),
        ),
        migrations.AddConstraint(
            model_name='tblavis',
            constraint=models.CheckConstraint(condition=models.Q(('note__gte', 1), ('note__lte', 5)), name='tblavis_note_valide_final'),
        ),
    ]
