# Generated by Django 5.1.4 on 2025-06-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0015_tblavisstatut_alter_tblavis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblavisstatut',
            name='description',
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
